# Generated by Django 5.2 on 2025-05-19 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuario_ni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva_ambiente',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='A Disciplina:'),
        ),
        migrations.AlterField(
            model_name='reserva_ambiente',
            name='professor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'P'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Escolha qual Professor:'),
        ),
        migrations.AlterField(
            model_name='reserva_ambiente',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sala', verbose_name='Escolha a sala da Palestra:'),
        ),
    ]
